#!/bin/bash

OPTIND=1

usage () {
echo "
Usage: . ./aws-auth.sh options

options:
   -m   arn of your virtual mfa device
   -t   token generated by your mfa device
"
   return
}

while getopts "m:t:" OPTION
do
  case $OPTION in
    m)
      mfa_serial_number=$OPTARG
      ;;
    t)
      token_code=$OPTARG
      ;;
    *)
      usage;
      return 1
      ;;
  esac
done

shift "$((OPTIND-1))"

if [ ! "$mfa_serial_number" ] || [ ! "$token_code" ]
then
  usage
  return 1
else
  unset AWS_ACCESS_KEY_ID
  unset AWS_SECRET_ACCESS_KEY
  unset AWS_SESSION_TOKEN

  output=($(aws sts get-session-token --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' --output text --serial-number $mfa_serial_number --token-code $token_code))
  export AWS_ACCESS_KEY_ID="${output[0]}" AWS_SECRET_ACCESS_KEY="${output[1]}" AWS_SESSION_TOKEN="${output[2]}"

  echo "token_code: $token_code"
  echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
  echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
  echo "AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN"
fi
