#!/bin/bash

function usage () {
   cat <<EOF

Usage: $0 options

options:
   -m   arn of your virtual mfa device
   -t   token generated by your mfa device
EOF
   return
}


while getopts "m:t:" OPTION
do
  case $OPTION in
    m)
      mfa_serial_number=$OPTARG
      ;;
    t)
      token_code=$OPTARG
      ;;
    *)
      usage;
      return 1
      ;;
  esac
done

if [ ! "$mfa_serial_number" ] || [ ! "$token_code" ]
then
  usage
  return 1
else
  unset AWS_ACCESS_KEY_ID
  unset AWS_SECRET_ACCESS_KEY
  unset AWS_SESSION_TOKEN

  output=$(aws sts get-session-token --serial-number $mfa_serial_number --token-code $token_code)

  export AWS_ACCESS_KEY_ID=$(echo $output | jq -r '.Credentials.AccessKeyId')
  export AWS_SECRET_ACCESS_KEY=$(echo $output | jq -r '.Credentials.SecretAccessKey')
  export AWS_SESSION_TOKEN=$(echo $output | jq -r '.Credentials.SessionToken')

  echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
  echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
  echo "AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN"
fi

